Traceback (most recent call last):
  File "/Users/luo/miniconda3/envs/venv-pyrsimg/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/luo/miniconda3/envs/venv-pyrsimg/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/luo/miniconda3/envs/venv-pyrsimg/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 158, in wrapped
    return _runner_map[name].run(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/luo/miniconda3/envs/venv-pyrsimg/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 125, in run
    return fut.result(None)
           ^^^^^^^^^^^^^^^^
  File "/Users/luo/miniconda3/envs/venv-pyrsimg/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/luo/miniconda3/envs/venv-pyrsimg/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/luo/miniconda3/envs/venv-pyrsimg/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/luo/miniconda3/envs/venv-pyrsimg/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/luo/miniconda3/envs/venv-pyrsimg/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import os
from pyrsimg import readTiff
from pyrsimg import imgShow, imsShow
from pyrsimg import img2patch
from pyrsimg import crop2size, crop2extent
import matplotlib.pyplot as plt
import numpy as np

------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 2[0m
[1;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mos[39;00m
[0;32m----> 2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpyrsimg[39;00m [38;5;28;01mimport[39;00m readTiff
[1;32m      3[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpyrsimg[39;00m [38;5;28;01mimport[39;00m imgShow, imsShow
[1;32m      4[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpyrsimg[39;00m [38;5;28;01mimport[39;00m img2patch

[0;31mModuleNotFoundError[0m: No module named 'pyrsimg'

